// Shared helpers: real service responses (test/fixtures, generated by
// research/tests/service/make_dart_fixtures.py) served by a mock HTTP client.

import 'dart:convert';
import 'dart:io';

import 'package:http/http.dart' as http;
import 'package:http/testing.dart';
import 'package:reflicaa/services/reflica_api.dart';

Map<String, dynamic> fixture(String name) =>
    jsonDecode(File('test/fixtures/$name').readAsStringSync()) as Map<String, dynamic>;

/// Mock backend: maps "METHOD /path" to (status, fixture); records requests.
class FakeBackend {
  final Map<String, (int, Map<String, dynamic>)> routes;
  final requests = <(String, Map<String, dynamic>?)>[];
  FakeBackend(this.routes);

  late final http.Client client = MockClient((req) async {
    final key = '${req.method} ${req.url.path}';
    requests.add((key, req.body.isEmpty ? null : jsonDecode(req.body) as Map<String, dynamic>));
    final r = routes[key];
    if (r == null) return http.Response('{"error":{"code":"not_found","message":"no route"}}', 404);
    return http.Response(jsonEncode(r.$2), r.$1, headers: {'content-type': 'application/json'});
  });

  ReflicaApi api() => ReflicaApi(baseUrl: 'http://reflica.test', client: client);

  Map<String, dynamic>? lastBody(String key) =>
      requests.lastWhere((r) => r.$1 == key).$2;
}
